### ISSUE TITLE
Greetings!

### ISSUE THREAD

**Issue by Thraka** [derrickcreamer/SunshineConsole#1]
Not an issue :smiley: 

i'm always interested in console frameworks. I have a similar framework I've been developing over the last 6 years. It's built on MonoGame so it supports OpenGL. I contributor came along and ported for Linux and MacOS support.

https://github.com/Thraka/SadConsole

Perhaps we can collaborate?

**Comment by derrickcreamer** [comment]
Hey, Thraka. Sunshine Console will remain minimal and simple - it's basically done! - but feel free to email me to discuss console frameworks. (I'm on gmail, same as my username here.)
