### ISSUE TITLE
Segmentation fault in Mono under Linux

### ISSUE THREAD

**Issue by mikezila** [derrickcreamer/SunshineConsole#2]
Does SunshineConsole currently work under Linux/OSX?  I figure it would since OpenTK is ported to everything under the sun, but trying to run even the simplest project gives me a segmentation fault right out of the gate.

**Comment by derrickcreamer** [comment]
My linux box died before I could test SSC on it. However, I expected it to work, because I use very similar code in another project that _was_ confirmed to run on linux. Is there any more info on the error?

**Comment by mikezila** [comment]
It looks like it's not your fault.  I had a PlayStation 4 pad plugged in that seems to have been causing the issue.  It causes something in sdl's joypad code to crash and burn.  I noticed if I wasn't `using OpenTK.Input` and omitted `console.KeyPressed` from the main loop it worked fine.

After unplugging the pad it works as expected.  Sweet library, by the way.

**Comment by derrickcreamer** [comment]
Oh, fantastic. I'm glad you're finding it useful.
