### ISSUE TITLE
Sunshine Console font

### ISSUE THREAD

**Issue by barborik** [derrickcreamer/SunshineConsole#5]
Hey, I'm really sorry for doing it this way but I haven't found any other method to contact you. I'm working on a [Java Sunshine Console port](https://github.com/Barbo24/JSunshineConsole) and I would love to use the same font as you. I'm quite new and there is no way I could figure out how to use the png file as a font. Is there a .ttf version or something? Thanks in advance

**Comment by derrickcreamer** [comment]
Hey! I'm afraid there is no .ttf -- I find them a pain to work with. (I'm
using MSDF fonts these days so I can continue to avoid font readers.)
I can tell you that this specific font was frankensteined together from a
few different sources, including the classic IBM VGA8 font. The smaller
glyphs I'm less sure about, but they look pretty close to the ones found
here: https://int10h.org/oldschool-pc-fonts/fontlist/font?dos-v_re_jpn12
... and then I remember that I modified a few characters directly to suit
my tastes.

Sounds like your best bet probably involves converting *something* to TTF,
although I'm not sure what starting point would be easiest. Hope that helps
you in some way - good luck!

**Comment by barborik** [comment]
Thank you so much, I think I'm gonna just man up and try to do it the same way you did.
